 # <div style="text-align: center">Linear Algebra for Data Scientists
<div style="text-align: center">
Having a basic knowledge of linear algebra is one of the requirements for any data scientist. In this tutorial we will try to cover all the necessary concepts related to linear algebra.

 <a id="top"></a> <br>
## Notebook  Content
1. [Introduction](#1)
1. [What is Linear Algebra?](#2)
1. [Notation ](#2)
1. [Matrix Multiplication](#3)
    1. [Vector-Vector Products](#31)
    1. [Outer Product of Two Vectors](#32)
    1. [Matrix-Vector Products](#33)
    1. [Matrix-Matrix Products](#34)
1. [Identity Matrix](#4)
1. [Diagonal Matrix](#5)
1. [Transpose of a Matrix](#6)
1. [Symmetric Metrices](#7)
1. [The Trace](#8)
1. [Norms](#9)
1. [Linear Independence and Rank](#10)
1. [Subtraction and Addition of Metrices](#11)
    1. [Inverse](#111)
1. [Orthogonal Matrices](#12)
1. [Range and Nullspace of a Matrix](#13)
1. [Determinant](#14)


<a id="1"></a> <br>
#  1-Introduction
This is the third step of the [10 Steps to Become a Data Scientist](https://www.kaggle.com/mjbahmani/10-steps-to-become-a-data-scientist).
we will cover following topic:
1. notation
1. Matrix Multiplication
1. Identity Matrix
1. Diagonal Matrix
1. Transpose of a Matrix
1. The Trace
1. Norms
1. Tensors
1. Hyperplane
1. Eigenvalues and Eigenvectors

## What is linear algebra?
**Linear algebra** is the branch of mathematics that deals with **vector spaces**. good understanding of Linear Algebra is intrinsic to analyze Machine Learning algorithms, especially for **Deep Learning** where so much happens behind the curtain.you have my word that I will try to keep mathematical formulas & derivations out of this completely mathematical topic and I try to cover all of subject that you need as data scientist.
<img src='https://camo.githubusercontent.com/e42ea0e40062cc1e339a6b90054bfbe62be64402/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3339313937313830393536333530383733382f3434323635393336333534333331383532382f7363616c61722d766563746f722d6d61747269782d74656e736f722e706e67' height=200 width=700>
[image credit: https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors/ ](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors/)
 <a id="top"></a> <br>

<a id="11"></a> <br>
## 1-1 Import

In [59]:
import matplotlib.patches as patch
import matplotlib.pyplot as plt
from scipy.stats import norm
from scipy import linalg
from numpy import poly1d
from sklearn import svm
import tensorflow as tf
import pandas as pd
import numpy as np
import glob
import sys
import os

<a id="12"></a> <br>
##  1-2 Setup

In [60]:
%matplotlib inline
%precision 4
plt.style.use('ggplot')
np.set_printoptions(suppress=True)

<a id="2"></a> <br>
# 2- What is Linear Algebra?
Linear algebra is the branch of mathematics concerning linear equations such as
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/f4f0f2986d54c01f3bccf464d266dfac923c80f3'>
Linear algebra is central to almost all areas of mathematics. [6]
<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Linear_subspaces_with_shading.svg/800px-Linear_subspaces_with_shading.svg.png' height=400 width=400>
[wikipedia](https://en.wikipedia.org/wiki/Linear_algebra#/media/File:Linear_subspaces_with_shading.svg)


In [61]:
# let see how to create a multi dimentional Array with Numpy
a = np.zeros((2, 3, 4))
#l = [[[ 0.,  0.,  0.,  0.],
    #      [ 0.,  0.,  0.,  0.],
     #     [ 0.,  0.,  0.,  0.]],
     #     [[ 0.,  0.,  0.,  0.],
    #      [ 0.,  0.,  0.,  0.],
     #     [ 0.,  0.,  0.,  0.]]]
print(a)
print(a.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)


In [62]:

# Declaring Vectors

x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))

# This does'nt give the vector addition.
print(x + y)

# Vector addition using Numpy

z = np.add(x, y)
print(z)
print(type(z))

# Vector Cross Product
'''
# Calculating the cross product of A and B
cross_product = [
    A[1]*B[2] - A[2]*B[1],  # i component
    -(A[0]*B[2] - A[2]*B[0]),  # j component
    A[0]*B[1] - A[1]*B[0]  # k component
]
'''
mul = np.cross(x, y)
print(mul)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
<class 'numpy.ndarray'>
[-3  6 -3]


## 2-1 What is Vectorization?
In mathematics, especially in linear algebra and matrix theory, the vectorization of a matrix is a linear transformation which converts the matrix into a column vector. Specifically, the vectorization of an m × n matrix A, denoted vec(A), is the mn × 1 column vector obtained by stacking the columns of the matrix A on top of one another:
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/30ca6a8b796fd3a260ba3001d9875e990baad5ab'>
[wikipedia](https://en.wikipedia.org/wiki/Vectorization_(mathematics) )

Vectors of the length $n$ could be treated like points in $n$-dimensional space. One can calculate the distance between such points using measures like [Euclidean Distance](https://en.wikipedia.org/wiki/Euclidean_distance). The similarity of vectors could also be calculated using [Cosine Similarity](https://en.wikipedia.org/wiki/Cosine_similarity).
###### [Go to top](#top)

<a id="3"></a> <br>
## 3- Notation
<img src='http://s8.picofile.com/file/8349058626/la.png'>
[linear.ups.edu](http://linear.ups.edu/html/notation.html)

<a id="4"></a> <br>
## 4- Matrix Multiplication
<img src='https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.gif'>

[mathsisfun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

The result of the multiplication of two matrixes $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$ is the matrix:

In [124]:
# initializing matrices
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

In [116]:
x.shape

(2, 2)

$C = AB \in \mathbb{R}^{m \times n}$

That is, we are multiplying the columns of $A$ with the rows of $B$:

$C_{ij}=\sum_{k=1}^n{A_{ij}B_{kj}}$
<img src='https://cdn.britannica.com/06/77706-004-31EE92F3.jpg'>
[reference](https://cdn.britannica.com/06/77706-004-31EE92F3.jpg)

The number of columns in $A$ must be equal to the number of rows in $B$.

###### [Go to top](#top)

In [117]:
x

array([[1, 2],
       [4, 5]])

In [118]:
y

array([[ 7,  8],
       [ 9, 10]])

In [119]:
x+y

array([[ 8, 10],
       [13, 15]])

In [120]:
# initializing matrices
x = np.array([[1, 2]])
y = np.array([[7, 8]])

In [121]:
x+y

array([[ 8, 10]])

In [122]:
x=[1, 2]
y=[7, 8]
x+y

[1, 2, 7, 8]

In [123]:
np.add(x,y)

array([ 8, 10])

In [125]:
# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (np.add(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]


In [126]:
# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (np.subtract(x,y))

The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]


In [127]:
x-y

array([[-6, -6],
       [-5, -5]])

In [128]:
# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (np.divide(x,y))

The element wise division of matrix is : 
[[0.1429 0.25  ]
 [0.4444 0.5   ]]


In [129]:
# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (np.multiply(x,y))

The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]


<a id="41"></a> <br>
## 4-1 Vector-Vector Products

numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)[source]
Return the cross product of two (arrays of) vectors.[scipy](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.cross.html)
<img src='http://gamedevelopertips.com/wp-content/uploads/2017/11/image8.png'>
[image-credits](http://gamedevelopertips.com)

In [130]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

We define the vectors $x$ and $y$ using *numpy*:

In [136]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)

x: [1 2 3 4]
y: [5 6 7 8]


In [137]:
x*y

array([ 5, 12, 21, 32])

We can now calculate the $dot$ or $inner product$ using the *dot* function of *numpy*:

In [138]:
np.dot(x, y)

70

The order of the arguments is irrelevant:

In [139]:
np.dot(y, x)

70

Note that both vectors are actually **row vectors** in the above code. We can transpose them to column vectors by using the *shape* property:

In [140]:
x.shape

(4,)

In [144]:
print("x:", x)
x.shape = (4, 1)
print("xT:", x)
print(x.shape)
print("y:", y)
y.shape = (4, 1)
print("yT:", y)
print(y.shape)

x: [1 2 3 4]
xT: [[1]
 [2]
 [3]
 [4]]
(4, 1)
y: [5 6 7 8]
yT: [[5]
 [6]
 [7]
 [8]]
(4, 1)


In fact, in our understanding of Linear Algebra, we take the arrays above to represent **row vectors**. *Numpy* treates them differently.

We see the issues when we try to transform the array objects. Usually, we can transform a row vector into a column vector in *numpy* by using the *T* method on vector or matrix objects:
###### [Go to top](#top)

In [145]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)
print(y.T.shape)

x: [1 2 3 4]
y: [5 6 7 8]
xT: [1 2 3 4]
yT: [5 6 7 8]
(4,)


The problem here is that this does not do, what we expect it to do. It only works, if we declare the variables not to be arrays of numbers, but in fact a matrix:

In [147]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)
print(x.T.shape)

x: [[1 2 3 4]]
y: [[5 6 7 8]]
xT: [[1]
 [2]
 [3]
 [4]]
yT: [[5]
 [6]
 [7]
 [8]]
(4, 1)


Note that the *numpy* functions *dot* and *outer* are not affected by this distinction. We can compute the dot product using the mathematical equation above in *numpy* using the new $x$ and $y$ row vectors:
###### [Go to top](#top)

In [75]:
print("x:", x)
print("y:", y.T)
np.dot(x, y.T)

x: [[1 2 3 4]]
y: [[5]
 [6]
 [7]
 [8]]


array([[70]])

Or by reverting to:

In [148]:
print("x:", x.T)
print("y:", y)
print(np.dot(y, x.T))
print(np.dot(y, x.T).shape)

x: [[1]
 [2]
 [3]
 [4]]
y: [[5 6 7 8]]
[[70]]
(1, 1)


To read the result from this array of arrays, we would need to access the value this way:

In [77]:
np.dot(y, x.T)[0][0]

70

<a id="42"></a> <br>
## 4-2 Outer Product of Two Vectors
Compute the outer product of two vectors.

In [78]:
x = np.array([[1, 2, 3, 4]])
print("x:", x)
print("xT:", np.reshape(x, (4, 1)))
print("xT:", x.T)
print("xT:", x.transpose())

x: [[1 2 3 4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]


Example
###### [Go to top](#top)

We can now compute the **outer product** by multiplying the column vector $x$ with the row vector $y$:

In [149]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
x.T * y

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [150]:
x

array([[1, 2, 3, 4]])

In [151]:
x.T

array([[1],
       [2],
       [3],
       [4]])

In [152]:
y

array([[5, 6, 7, 8]])

*Numpy* provides an *outer* function that does all that:

In [80]:
np.outer(x, y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

Note, in this simple case using the simple arrays for the data structures of the vectors does not affect the result of the *outer* function:

In [81]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.outer(x, y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

<a id="43"></a> <br>
## 4-3 Matrix-Vector Products
Use numpy.dot or a.dot(b). See the documentation [here](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html).

In [82]:
a = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print (a.dot(b))

[16  6  8]


Using *numpy* we can compute $Ax$:

In [83]:
A = np.array([[4, 5, 6],
             [7, 8, 9]])
x = np.array([1, 2, 3])
A.dot(x)

array([32, 50])

<a id="44"></a> <br>
## 4-4 Matrix-Matrix Products

In [84]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [85]:
matrix1 = np.matrix(a)
matrix2 = np.matrix(b)

In [86]:
matrix1 + matrix2

matrix([[5, 1],
        [2, 3]])

In [87]:
matrix1 - matrix2

matrix([[-3, -1],
        [-2, -1]])

<a id="441"></a> <br>
### 4-4-1  Multiplication

In [88]:
np.dot(matrix1, matrix2)

matrix([[4, 1],
        [2, 2]])

In [89]:

matrix1 * matrix2

matrix([[4, 1],
        [2, 2]])

<a id="5"></a> <br>
## 5- Identity Matrix

numpy.identity(n, dtype=None)

Return the identity array.
[source](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.identity.html)

In [90]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

How to create *identity matrix* in *numpy*  

In [153]:
identy = np.array([[21, 5, 7],[9, 8, 16]])
print("identy:", identy)

identy: [[21  5  7]
 [ 9  8 16]]


In [154]:
identy.shape

(2, 3)

In [155]:
np.identity(identy.shape[1], dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [157]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
np.identity(identy.shape[0], dtype="int")

array([[1, 0],
       [0, 1]])

<a id="51"></a> <br>
### 5-1  Inverse Matrices

In [158]:
matrix

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

In [159]:
inverse = np.linalg.inv(matrix1)
print(inverse)

[[1. 0.]
 [0. 1.]]


<a id="6"></a> <br>
## 6- Diagonal Matrix

In *numpy* we can create a *diagonal matrix* from any given matrix using the *diag* function:

In [163]:
import numpy as np
A = np.array([[0,   1,  2,  3],
              [4,   5,  6,  7],
              [8,   9, 10, 11],
              [12, 13, 14, 15]])
np.diag(A)

array([ 0,  5, 10, 15])

2

In [164]:
np.diag(A, k=1)

array([ 1,  6, 11])

In [165]:
np.diag(A, k=-1)

array([ 4,  9, 14])

In [167]:
np.diag(A, k=3)

array([3])

<a id="7"></a> <br>
## 7- Transpose of a Matrix
For reading about Transpose of a Matrix, you can visit [this link](https://py.checkio.org/en/mission/matrix-transpose/)

In [99]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [100]:
a.transpose()

array([[1, 3],
       [2, 4]])

<a id="8"></a> <br>
## 8- Symmetric Matrices
In linear algebra, a symmetric matrix is a square matrix that is equal to its transpose. Formally,
<img src='https://wikimedia.org/api/rest_v1/media/math/render/svg/ad8a5a3a4c95de6f7f50b0a6fb592d115fe0e95f'>

[wikipedia](https://en.wikipedia.org/wiki/Symmetric_matrix)

In [101]:
N = 100
b = np.random.random_integers(-2000,2000,size=(N,N))
b_symm = (b + b.T)/2

<ipython-input-101-fa8b13967f1b>:2: DeprecationWarning: This function is deprecated. Please call randint(-2000, 2000 + 1) instead
  b = np.random.random_integers(-2000,2000,size=(N,N))


<a id="9"></a> <br>
## 9-The Trace
Return the sum along diagonals of the array.

In [102]:
np.trace(np.eye(3))

3.0

In [103]:
print(np.trace(matrix1))

2


In [104]:
det = np.linalg.det(matrix1)
print(det)

1.0


<a id="10"></a> <br>
# 10- Norms
numpy.linalg.norm
This function is able to return one of eight different matrix norms, or one of an infinite number of vector norms (described below), depending on the value of the ord parameter. [scipy](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html)

 <a id="top"></a> <br>

In [105]:
v = np.array([1,2,3,4])
norm.median(v)

array([1., 2., 3., 4.])

<a id="11"></a> <br>
# 11- Linear Independence and Rank
How to identify the linearly independent rows from a matrix?

In [106]:
#How to find linearly independent rows from a matrix
matrix = np.array(
    [
        [0, 1 ,0 ,0],
        [0, 0, 1, 0],
        [0, 1, 1, 0],
        [1, 0, 0, 1]
    ])

lambdas, V =  np.linalg.eig(matrix.T)
# The linearly dependent row vectors
print (matrix[lambdas == 0,:])

[[0 1 1 0]]


<a id="12"></a> <br>
# 12-  Subtraction and Addition of Metrices

In [107]:
import numpy as np
print("np.arange(9):", np.arange(9))
print("np.arange(9, 18):", np.arange(9, 18))
A = np.arange(9, 18).reshape((3, 3))
B = np.arange(9).reshape((3, 3))
print("A:", A)
print("B:", B)

np.arange(9): [0 1 2 3 4 5 6 7 8]
np.arange(9, 18): [ 9 10 11 12 13 14 15 16 17]
A: [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
B: [[0 1 2]
 [3 4 5]
 [6 7 8]]


We can now add and subtract the two matrices $A$ and $B$:

In [108]:
A + B

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [109]:
A - B

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

<a id="121"></a> <br>
## 12-1 Inverse
We use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.[tutorialspoint](https://www.tutorialspoint.com/numpy/numpy_inv.htm)

In [110]:
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)
print (x )
print (y )
print (np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


<a id="13"></a> <br>
## 13- Orthogonal Matrices
How to create random orthonormal matrix in python numpy

In [111]:
## based on https://stackoverflow.com/questions/38426349/how-to-create-random-orthonormal-matrix-in-python-numpy
def rvs(dim=3):
     random_state = np.random
     H = np.eye(dim)
     D = np.ones((dim,))
     for n in range(1, dim):
         x = random_state.normal(size=(dim-n+1,))
         D[n-1] = np.sign(x[0])
         x[0] -= D[n-1]*np.sqrt((x*x).sum())
         # Householder transformation
         Hx = (np.eye(dim-n+1) - 2.*np.outer(x, x)/(x*x).sum())
         mat = np.eye(dim)
         mat[n-1:, n-1:] = Hx
         H = np.dot(H, mat)
         # Fix the last sign such that the determinant is 1
     D[-1] = (-1)**(1-(dim % 2))*D.prod()
     # Equivalent to np.dot(np.diag(D), H) but faster, apparently
     H = (D*H.T).T
     return H

<a id="14"></a> <br>
## 14- Range and Nullspace of a Matrix

In [112]:
from scipy.linalg import null_space
A = np.array([[1, 1], [1, 1]])
ns = null_space(A)
ns * np.sign(ns[0,0])  # Remove the sign ambiguity of the vector

array([[ 0.7071],
       [-0.7071]])

<a id="15"></a> <br>
# 15-  Determinant
Compute the determinant of an array

In [113]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004